### ISSUE TITLE
AWS Key Exposed

### ISSUE THREAD

**Issue by 726973696e6773756e** [Clemson-CPSC-4910/s18-moliere-one#1]
Hey Rushton,

https://github.com/Clemson-CPSC-4910/s18-moliere-one/blob/master/config.moliere.json

Your AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY are exposed. I would recommend adding config.moliere.json to your git ignore list. Furthermore I would also suggest resetting your IAM credentials as someone else could use these on your bucket externally.

Many Thanks
726973696e6773756e

**Comment by 726973696e6773756e** [comment]
Hi!

Your keys are still active at https://github.com/Clemson-CPSC-4910/s18-moliere-one/blob/master/backend-api/config.moliere.json as well.

Many Thanks
726973696e6773756e

**Comment by timschwab** [comment]
Fixed.
